package rules.compound;

import rs.sbnz.model.Request;
import rs.sbnz.model.events.AttackEvent;
import rs.sbnz.model.AttackType;
import rs.sbnz.model.AttackSeverity;

rule "Two SuperHigh (or above) attacks of different type"
    when
        $attack1: AttackEvent(
            $type1: type, 
            severity >= AttackSeverity.SUPERHIGH,
            madeAwareOf == false
        )
        $attack2: AttackEvent(
            type != $type1, 
            severity >= AttackSeverity.SUPERHIGH,
            madeAwareOf == false,
            this after $attack1 
        )
    then
        System.out.println("Two super high attacks of different type! Aaah!");
        modify($attack1) {
            setMadeAwareOf(true);
        }
        modify($attack2) {
            setMadeAwareOf(true);
        }
end

// rule "Four attacks of any severity, each with a different attack"

// end

// rule "One Critical attack"

// end