package rules.test;

import rs.sbnz.model.Request;

rule "Source IP is Dest IP"
    when
        Number(intValue >= 1000) from accumulate(
            $r: Request(
                $id: id,
                $srcIp: srcIp, 
                $destIp: destIp, 
                $srcIp == $destIp
            ) over window:time(1m),
            count($id)
        )
    then
        System.out.println("TCP Flood Attack!");
end