template header
numberOfRequests
timeFrame

package templateRulesTwo;

import rs.sbnz.model.Request;
import rs.sbnz.model.events.AttackEvent;
import rs.sbnz.model.AttackType;
import rs.sbnz.model.AttackSeverity;
import rs.sbnz.model.Alarm;
import rs.sbnz.model.AlarmSeverity;
import rs.sbnz.model.AlarmType;

template "dosTemplate"

rule "Detect DOS when @{numberOfRequests} requests are made in @{timeFrame}"
    salience 1880
    when
        Number(intValue >= @{numberOfRequests}) from accumulate(
            $r: Request(
                isRejected == false,
                $id: id
            ) over window:time(@{timeFrame}),
            count($id)
        )
        not AttackEvent(
            type == AttackType.DISTRIBUTED_DENIAL_OF_SERVICE
        ) over window:time(@{timeFrame})
        not AttackEvent(
            type == AttackType.DENIAL_OF_SERVICE
        ) over window:time(@{timeFrame})
    then
        System.out.printf("DOS attack!\n");
        insert(new Alarm(AlarmSeverity.HIGH, AlarmType.DOS, "A DOS has been detected."));
        insert(new AttackEvent(AttackType.DENIAL_OF_SERVICE, AttackSeverity.SUPERHIGH));
end

end template