package reports;

import rs.sbnz.model.events.FailedLoginEvent;
import rs.sbnz.model.events.BlockEvent;
import rs.sbnz.model.events.AttackEvent;
import rs.sbnz.model.AttackType;

// TODO:
// templates

rule "Show attack events of type AUTHENTICATION in last 24 hours if there is more than 3 of them"
    agenda-group "reports"
    when
        $e1: AttackEvent(type == AttackType.AUTHENTICATION) over window:time(24h)
        Number(intValue >= 2) from accumulate(
            $e2: AttackEvent(
                this != $e1,
                type == AttackType.AUTHENTICATION
            ) over window:time(24h),
            count($e2)
        )
    then
        // Note that we don't print the timestamp in the actual rule, but if need be can retrieve it through
        // insert's fact handle's getStartTimestamp()
        // https://lists.jboss.org/archives/list/rules-users@lists.jboss.org/thread/FOYSWWYQ6H3IQ22I7YWBGJQSMJWM6NEE/
        System.out.println($e1);
end

rule "Show attack events of all types in last 24 hours if there is more than 3 of them"
    agenda-group "reports2"
    when
        $e1: AttackEvent() over window:time(24h)
        Number(intValue >= 2) from accumulate(
            $e2: AttackEvent(
                this != $e1
            ) over window:time(24h),
            count($e2)
        )
    then
        System.out.println($e1);
end

rule "Show failed login attempts from same ip address in last 24 hours if there is more than 3 of them"
    agenda-group "reports"
    when
        $e1: FailedLoginEvent($ip: ip) over window:time(24h)
        Number(intValue >= 2) from accumulate(
            $e2: FailedLoginEvent(
                this != $e1,
                ip == $ip
            ) over window:time(24h),
            count($e2)
        )
    then
        System.out.println($e1);
end

rule "Show block events for same ip address in last 24 hours if there is more than 3 of them"
    agenda-group "reports"
    when
        $e1: BlockEvent($ip: ip) over window:time(24h)
        Number(intValue >= 2) from accumulate(
            $e2: BlockEvent(
                this != $e1,
                ip == $ip
            ) over window:time(24h),
            count($e2)
        )
    then
        System.out.println($e1);
end